[phases.setup]
nixPkgs = ["nodePackages.npm", "nodejs", "chromium", "playwright"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build", "npx playwright install chromium", "npx prisma db push --accept-data-loss"]

[start]
cmd = "npm run start"
